# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes to
# /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{ imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];

  boot.initrd.luks.devices = {
    crypt = {
         device = "/dev/disk/by-uuid/1cbad51c-77c5-4807-97e2-ef14d023a10e";
         preLVM = true;
    };
  };

  boot.kernelModules = [ "kvm-intel" ]; boot.extraModulePackages = [ ];
  fileSystems."/" = {
    device = "/dev/mapper/evo-nix";
    fsType = "ext4";
    };

  fileSystems."/boot" = { device =
    "/dev/disk/by-uuid/30b66060-c0ff-4d84-a8bb-e43c6892b290";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" = { device = "/dev/disk/by-uuid/8492-ECF4";
      fsType = "vfat";
    };

  fileSystems."/home" = { device =
    "/dev/mapper/evo-home";
      fsType = "ext4";
    };

  swapDevices = [ { device =
    "/dev/mapper/evo-swap"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of
  # scripted networking (the default) this is the recommended approach.
  # When using systemd-networkd it's still possible to use this option,
  # but it's recommended to use it in conjunction with explicit
  # per-interface declarations with
  # `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp166s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault
  config.hardware.enableRedistributableFirmware;
}
