#!/bin/bash

if [ -z "$1" ]; then
    BRANCH=$(git symbolic-ref --short HEAD)

    if [ -z "$BRANCH" ]; then
        >&2 echo "Specify a branch!"
        exit 1
    fi
else
    BRANCH="$1"
fi

git push -u origin $BRANCH && \
    hub pull-request
