---
- name: set up a development environment
  connection: local
  hosts: localhost
  vars:
    yq_version: 4.44.2
    kind_version: v0.31.0
    cloud_provider_kind_version: 0.10.0
    up_version: 0.44.3
    jolt_version: 1.1.3
    helmfile_version: 1.2.3
  tasks:
  - name: install fish
    block:
    - name: "fish repo"
      shell:
        cmd: add-apt-repository -y ppa:fish-shell/release-4
        creates: "/etc/apt/sources.list.d/fish-shell-ubuntu-release-4-{{ ansible_facts['distribution_release'] }}.sources"
      become: true
    - name: "install fish"
      apt:
        name: fish
      become: true
    - name: "set shell"
      user:
        name: "{{ ansible_facts['user_id'] }}"
        shell: /bin/fish
      become: true
  - name: ".local/bin"
    file:
      state: "directory"
      path: "{{ ansible_user_dir}}/.local/bin"
  - name: "checkout spacemacs"
    git:
      repo: "https://github.com/syl20bnr/spacemacs"
      dest: "{{ ansible_facts['user_dir'] }}/.emacs.d"
      update: yes
      version: develop
  - name: "install dev tools"
    apt:
      name:
      - build-essential
      - ripgrep
      - jq
      - gist
      - direnv
      - gopls
      - pre-commit
      - emacs-pgtk
      - fonts-inconsolata
      - clamav # compliance
      - htop
    become: true
  - name: "install yq"
    get_url:
      url: "https://github.com/mikefarah/yq/releases/download/v{{ yq_version }}/yq_linux_amd64"
      dest: "{{ ansible_facts['user_dir'] }}/.local/bin/yq"
      mode: 'u+rwx'
  - name: "install kind"
    get_url:
      url: "https://kind.sigs.k8s.io/dl/{{ kind_version }}/kind-linux-amd64"
      dest: "{{ ansible_facts['user_dir'] }}/.local/bin/kind"
      mode: 'u+rwx'
  - name: "install helmfile"
    unarchive:
      remote_src: true
      src: "https://github.com/helmfile/helmfile/releases/download/v{{ helmfile_version }}/helmfile_{{ helmfile_version }}_linux_amd64.tar.gz"
      creates: "{{ ansible_facts['user_dir'] }}/.local/bin/helmfile"
      dest: "{{ ansible_facts['user_dir'] }}/.local/bin"
      include: 'helmfile'
  - name: "cloud-provider-kind"
    block:
    - name: "cloud-provider-kind"
      unarchive:
        remote_src: true
        src: https://github.com/kubernetes-sigs/cloud-provider-kind/releases/download/v{{ cloud_provider_kind_version }}/cloud-provider-kind_{{ cloud_provider_kind_version }}_linux_amd64.tar.gz
        creates: "/usr/local/bin/.local/bin/cloud-provider-kind"
        dest: "/usr/local/bin/"
        include: 'cloud-provider-kind'
      become: true
    - name: 'cloud-provider-kind unit'
      register: cpk_unit
      copy:
        content: |
          [Unit]
          Description=
          After=network.target

          [Service]
          Type=simple
          User=
          ExecStart="/usr/local/bin/cloud-provider-kind"
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/cloud-provider-kind.service
      become: true
    - name: "start cloud-provider-kind service"
      systemd_service:
        name: cloud-provider-kind
        state: started
        daemon-reload: "{{ cpk_unit.changed }}"
      become: true
  - name: "latest ansible"
    block:
    - name: 'ansible ppa'
      shell:
        cmd: add-apt-repository -y ppa:ansible/ansible
        creates: "/etc/apt/sources.list.d/ansible-ubuntu-ansible-{{ ansible_facts['distribution_release'] }}.sources"
      become: true
    - name: "upgrade ansible"
      apt:
        name:
        # https://github.com/ansible/ansible/issues/86268
        - ansible-core=2.19.0-1ubuntu1
        - ansible
        allow_downgrade: true
      become: true
  - name: "add docker group"
    group:
      name: docker
    become: true
  - name: "add user to docker group"
    user:
      name: "{{ ansible_facts['user_id'] }}"
      groups:
      - docker
      append: true
    become: true
  - name: "upbound packages"
    block:
    - name: 'install up'
      apt:
        deb:  https://cli.upbound.io/stable/v{{ up_version }}/deb/up_{{ up_version }}_linux_amd64.deb
      become: true
    - name: 'install docker-credential-up'
      apt:
        deb:  https://cli.upbound.io/stable/v{{ up_version }}/deb/docker-credential-up_{{ up_version }}_linux_amd64.deb
      become: true
  - name: "install jolt"
    unarchive:
      remote_src: true
      src: "https://github.com/jordond/jolt/releases/download/{{ jolt_version }}/jolt-{{ jolt_version }}-linux-amd64.tar.gz"
      creates: "{{ ansible_facts['user_dir'] }}/.local/bin/jolt"
      dest: "{{ ansible_facts['user_dir'] }}/.local/bin"
      extra_opts:
      - "--strip=1"
  - name: "install aws-cli"
    block:
    - name: "download AWS CLI"
      unarchive:
        remote_src: true
        src: "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip"
        creates: "{{ ansible_facts['user_dir'] }}/.local/share/aws"
        dest: "{{ ansible_facts['user_dir'] }}/.local/share"
      register: aws_cli_archive
    - name: install AWS CLI
      shell:
        chdir: "{{ aws_cli_archive.dest }}"
        cmd: "./aws/install"
        creates: "/usr/local/bin/aws"
      when: "aws_cli_archive.changed"
      become: true
    # - name: "install session manager plugin"
    #   apt:
    #     deb: "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_amd64/session-manager-plugin.deb"
    #   become: true
  - name: "make directory"
    file:
      state: "directory"
      path: "{{ ansible_facts['user_dir']}}/.local/src"
  roles:
  - role: repo_with_key
    vars:
      repo_name: "docker"
      key_url:  "https://download.docker.com/linux/ubuntu/gpg"
      repo_url: "https://download.docker.com/linux/ubuntu/ {{ ansible_facts['distribution_release'] }} stable"
      package:
      - "docker-ce"
      - "docker-ce-cli"
      - "containerd.io"
      - "docker-buildx-plugin"
      - "docker-compose-plugin"
  - role: repo_with_key
    vars:
      repo_name: "helm"
      key_url: "https://packages.buildkite.com/helm-linux/helm-debian/gpgkey"
      repo_url: "https://packages.buildkite.com/helm-linux/helm-debian/any/ any main"
      package:
      - helm
  - role: repo_with_key
    vars:
      repo_name: "github"
      key_name: "github.gpg"
      key_url:  "https://cli.github.com/packages/githubcli-archive-keyring.gpg"
      repo_url: "https://cli.github.com/packages stable main"
      package:
      - "gh"
  - role: repo_with_key
    vars:
      repo_name: "kubernetes"
      key_url: https://pkgs.k8s.io/core:/stable:/v1.35/deb/Release.key
      repo_url: "https://pkgs.k8s.io/core:/stable:/v1.35/deb/ /"
      package:
      - "kubectl"
#  - role: emacs
  - role: cimon-io.asdf
    asdf_user: "{{ ansible_facts['user_id'] }}"
    asdf_group: "{{ ansible_facts['user_gid'] }}"
    asdf_plugins:
    - name: golang
      versions:
      - "1.25.7"
