---
- name: set up a development environment
  connection: local
  hosts: localhost
  vars:
    user: ellie
  tasks:
  - name: install zsh
    block:
    - apt:
        name: zsh
      become: true
    - user:
        name: "{{ user }}"
        shell: /bin/zsh
      become: true
  - name: "general utilities"
    block:
    - apt:
        name:
        - man
      become: true
  - name: install emacs
    block:
    - apt:
        name:
        - emacs
        - fonts-inconsolata
      become: true
    - git:
        repo: "https://github.com/syl20bnr/spacemacs"
        dest: "/home/{{ user }}/.emacs.d"
        update: no
        version: develop
  - name: install rust env
    block:
    - command: "curl -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path"
      args:
        creates: "~/.cargo/bin/rustup"
        
