---
- name: set up a development environment
  connection: local
  hosts: localhost
  vars:
    yq_version: 4.44.2
    kind_version: v0.31.0
    cloud_provider_kind_version: 0.10.0
    up_version: 0.45.0
    jolt_version: 1.1.3
    helmfile_version: 1.2.3
    actionlint_version: 1.7.11
    goreleaser_version: 2.14.1
    crank_version: 2.2.0
  tasks:
  - name: install fish
    block:
    - name: "fish repo"
      shell:
        cmd: add-apt-repository -y ppa:fish-shell/release-4
        creates: "/etc/apt/sources.list.d/fish-shell-ubuntu-release-4-{{ ansible_facts['distribution_release'] }}.sources"
      become: true
    - name: "install fish"
      apt:
        name: fish
      become: true
    - name: "set shell"
      user:
        name: "{{ ansible_facts['user_id'] }}"
        shell: /bin/fish
      become: true
  - name: ".local/bin"
    file:
      state: "directory"
      path: "{{ ansible_user_dir}}/.local/bin"
  - name: "crossplane-cli"
    get_url:
      url: "https://releases.crossplane.io/stable/v{{ crank_version }}/bin/linux_amd64/crank"
      mode: "u+rwx"
      dest: "{{ ansible_user_dir}}/.local/bin/crossplane"
  - name: "checkout spacemacs"
    git:
      repo: "https://github.com/syl20bnr/spacemacs"
      dest: "{{ ansible_facts['user_dir'] }}/.emacs.d"
      update: yes
      version: develop
  - name: "install dev tools"
    apt:
      name:
      - build-essential
      - ripgrep
      - jq
      - gist
      - direnv
      - gopls
      - pre-commit
      - emacs-pgtk
      - fonts-inconsolata
      - clamav # compliance
      - htop
      - net-tools
    become: true
  - name: "install yq"
    get_url:
      url: "https://github.com/mikefarah/yq/releases/download/v{{ yq_version }}/yq_linux_amd64"
      dest: "{{ ansible_facts['user_dir'] }}/.local/bin/yq"
      mode: 'u+rwx'
  - name: "install kind"
    get_url:
      url: "https://kind.sigs.k8s.io/dl/{{ kind_version }}/kind-linux-amd64"
      dest: "{{ ansible_facts['user_dir'] }}/.local/bin/kind"
      mode: 'u+rwx'
  - name: "install helmfile"
    unarchive:
      remote_src: true
      src: "https://github.com/helmfile/helmfile/releases/download/v{{ helmfile_version }}/helmfile_{{ helmfile_version }}_linux_amd64.tar.gz"
      creates: "{{ ansible_facts['user_dir'] }}/.local/bin/helmfile"
      dest: "{{ ansible_facts['user_dir'] }}/.local/bin"
      include: 'helmfile'
  - name: "install actionlint"
    unarchive:
      remote_src: true
      src: "https://github.com/rhysd/actionlint/releases/download/v{{ actionlint_version }}/actionlint_{{ actionlint_version }}_linux_amd64.tar.gz"
      creates: "{{ ansible_facts['user_dir'] }}/.local/bin/actionlint"
      dest: "{{ ansible_facts['user_dir'] }}/.local/bin"
      include: actionlint
  - name: "helm diff plugin"
    kubernetes.core.helm_plugin:
      plugin_path: https://github.com/databus23/helm-diff
      state: present
  - name: "cloud-provider-kind"
    block:
    # - name: "cloud-provider-kind"
    #   unarchive:
    #     remote_src: true
    #     src: https://github.com/kubernetes-sigs/cloud-provider-kind/releases/download/v{{ cloud_provider_kind_version }}/cloud-provider-kind_{{ cloud_provider_kind_version }}_linux_amd64.tar.gz
    #     creates: "/usr/local/bin/.local/bin/cloud-provider-kind"
    #     dest: "/usr/local/bin/"
    #     include: 'cloud-provider-kind'
    #   become: true
    - name: 'cloud-provider-kind unit'
      register: cpk_unit
      copy:
        content: |
          [Unit]
          Description=cloud-provider-kind daemon
          After=network.target

          [Service]
          Type=simple
          User=
          ExecStart="/usr/local/bin/cloud-provider-kind" --gateway-channel experimental
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/cloud-provider-kind.service
      become: true
    - name: "start cloud-provider-kind service"
      systemd_service:
        name: cloud-provider-kind
        state: "{{ cpk_unit.changed | ternary('restarted', 'started') }}"
        daemon-reload: "{{ cpk_unit.changed }}"
      become: true
  - name: "latest ansible"
    block:
    - name: 'ansible ppa'
      shell:
        cmd: add-apt-repository -y ppa:ansible/ansible
        creates: "/etc/apt/sources.list.d/ansible-ubuntu-ansible-{{ ansible_facts['distribution_release'] }}.sources"
      become: true
    - name: "upgrade ansible"
      apt:
        name:
        # https://github.com/ansible/ansible/issues/86268
        - ansible-core=2.19.0-1ubuntu1
        - ansible
        allow_downgrade: true
      become: true
  - name: "add docker group"
    group:
      name: docker
    become: true
  - name: "add user to docker group"
    user:
      name: "{{ ansible_facts['user_id'] }}"
      groups:
      - docker
      append: true
    become: true
  - name: "Install go-releaser"
    apt:
      deb: https://github.com/goreleaser/goreleaser/releases/download/v{{ goreleaser_version }}/goreleaser_{{ goreleaser_version }}_amd64.deb
    become: true
  - name: "upbound packages"
    block:
    - name: 'install up'
      apt:
        deb:  https://cli.upbound.io/stable/v{{ up_version }}/deb/up_{{ up_version }}_linux_amd64.deb
      become: true
    - name: 'install docker-credential-up'
      apt:
        deb:  https://cli.upbound.io/stable/v{{ up_version }}/deb/docker-credential-up_{{ up_version }}_linux_amd64.deb
      become: true
  - name: "install jolt"
    unarchive:
      remote_src: true
      src: "https://github.com/jordond/jolt/releases/download/{{ jolt_version }}/jolt-{{ jolt_version }}-linux-amd64.tar.gz"
      creates: "{{ ansible_facts['user_dir'] }}/.local/bin/jolt"
      dest: "{{ ansible_facts['user_dir'] }}/.local/bin"
      extra_opts:
      - "--strip=1"
  - name: "install aws-cli"
    block:
    - name: "download AWS CLI"
      unarchive:
        remote_src: true
        src: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        creates: "{{ ansible_facts['user_dir'] }}/.local/share/aws"
        dest: "{{ ansible_facts['user_dir'] }}/.local/share"
      register: aws_cli_archive
    - name: install AWS CLI
      shell:
        chdir: "{{ aws_cli_archive.dest }}"
        cmd: "./aws/install"
        creates: "/usr/local/bin/aws"
      when: "aws_cli_archive.changed"
      become: true
    # - name: "install session manager plugin"
    #   apt:
    #     deb: "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_amd64/session-manager-plugin.deb"
    #   become: true
  - name: "make directory"
    file:
      state: "directory"
      path: "{{ ansible_facts['user_dir']}}/.local/src"
  - name: gcloud proxies
    block:
    - name: 'gcloud iap dev proxy'
      register: iap_dev_unit
      copy:
        content: |
          [Unit]
          Description=
          After=network.target

          [Service]
          Type=simple
          User=
          ExecStart=gcloud compute start-iap-tunnel jump-dev 8888 --local-host-port=localhost:8888 --project=upbound-cloud-dev --zone us-west1-a
          Restart=on-failure

          [Install]
          WantedBy=default.target
        dest: "{{ ansible_facts['user_dir']}}/.config/systemd/user/gcloud-ip-proxy-dev.service"
    - name: "start cloud-provider-kind service"
      systemd_service:
        scope: user
        name: gcloud-ip-proxy-dev
        state: "{{ iap_dev_unit.changed | ternary('restarted', 'started') }}"
        daemon-reload: "{{ iap_dev_unit.changed }}"
    - name: 'gcloud iap prod proxy'
      register: iap_prod_unit
      copy:
        content: |
          [Unit]
          Description=
          After=network.target

          [Service]
          Type=simple
          User=
          ExecStart=gcloud compute start-iap-tunnel jump-production 8888 --local-host-port=localhost:8890 --project=upbound-cloud-production --zone us-west1-a
          Restart=on-failure

          [Install]
          WantedBy=default.target
        dest: "{{ ansible_facts['user_dir']}}/.config/systemd/user/gcloud-ip-proxy-prod.service"
    - name: "start cloud-provider-kind service"
      systemd_service:
        scope: user
        name: gcloud-ip-proxy-prod
        state: "{{ iap_prod_unit.changed | ternary('restarted', 'started') }}"
        daemon-reload: "{{ iap_prod_unit.changed }}"

  - name: keyd
    block:
    - name: "latest keyd"
      block:
      - name: "keyd ppa"
        shell:
          cmd: "add-apt-repository -y ppa:keyd-team/ppa"
          creates: "/etc/apt/sources.list.d/keyd-team-ubuntu-ppa-{{ ansible_facts['distribution_release'] }}.sources"
        become: true
        register: keyd_ppa
      - name: "keyd"
        apt:
          name: keyd
          update_cache: "{{ keyd_ppa.changed }}"
        become: true
      - name: "dvorak config"
        copy:
          content: |
            include layouts/dvorak

            [ids]
            0001:0001

            [global]
            default_layout = dvorak
          dest: /etc/keyd/default.conf
        become: true
        register: keyd_file
      - name: enable daemon
        systemd_service:
          name: keyd
          state: "started"
          enabled: true
        become: true
      - name: "bounce keyd"
        systemd_service:
          state: "reloaded"
        become: true
        when: keyd_file.changed
      # - name: 'ansible ppa'
      #   shell:
      #     cmd: ppa:keyd-team/ppa
      #     creates: "/etc/apt/sources.list.d/keyd-team-ubuntu-keyd-{{ ansible_facts['distribution_release'] }}.sources"
      #   become: true
  - name: "inotify limits"
    ansible.posix.sysctl:
      name: fs.inotify.max_user_watches
      value: '524288'
      state: present
      sysctl_set: true
    become: true
  - name: "inotify limits"
    ansible.posix.sysctl:
      name: fs.inotify.max_user_instances
      value: '1024'
      state: present
      sysctl_set: true
    become: true
  - name: "goimports"
    shell:
      cmd: "go install golang.org/x/tools/cmd/goimports@latest"
      creates: "{{ ansible_facts['user_dir'] }}/.local/bin/goimports"
    environment:
      GOBIN: "{{ ansible_facts['user_dir'] }}/.local/bin"
  - name: "theme grub"
    block:
    - name: check for background
      stat:
        path: "{{ ansible_facts['user_dir'] }}/Pictures/grubbg.png"
      register: grubpng
    - name: "copy to boot"
      register: bootpng
      when: grubpng.stat.exists
      copy:
        src: "{{ grubpng.stat.path }}"
        dest: "/boot/grub/grubbg.png"
      become: true
    - name: "set GRUB_BACKGROUND cfg"
      copy:
        content: |
          GRUB_BACKGROUND="/boot/grub/grubbg.png"
        dest: "/etc/default/grub.d/background.cfg"
      register: backgroundcfg
      become: true
    - name: "run update-grub"
      shell:
        cmd: update-grub
      become: true
      when: backgroundcfg.changed

  roles:
  - role: repo_with_key
    vars:
      repo_name: azure
      key_url: https://packages.microsoft.com/keys/microsoft.asc
      repo_url: "https://packages.microsoft.com/repos/azure-cli/ noble main" # no questing
      package:
      - azure-cli
  - role: repo_with_key
    vars:
      repo_name: gcloud
      key_url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      repo_url: https://packages.cloud.google.com/apt cloud-sdk main
      package:
      - "google-cloud-cli"
      - "google-cloud-cli-gke-gcloud-auth-plugin"
  - role: repo_with_key
    vars:
      repo_name: "docker"
      key_url:  "https://download.docker.com/linux/ubuntu/gpg"
      repo_url: "https://download.docker.com/linux/ubuntu/ {{ ansible_facts['distribution_release'] }} stable"
      package:
      - "docker-ce"
      - "docker-ce-cli"
      - "containerd.io"
      - "docker-buildx-plugin"
      - "docker-compose-plugin"
  - role: repo_with_key
    vars:
      repo_name: "helm"
      key_url: "https://packages.buildkite.com/helm-linux/helm-debian/gpgkey"
      repo_url: "https://packages.buildkite.com/helm-linux/helm-debian/any/ any main"
      package:
      - helm
  - role: repo_with_key
    vars:
      repo_name: "github"
      key_name: "github.gpg"
      key_url:  "https://cli.github.com/packages/githubcli-archive-keyring.gpg"
      repo_url: "https://cli.github.com/packages stable main"
      package:
      - "gh"
  - role: repo_with_key
    vars:
      repo_name: "kubernetes"
      key_url: https://pkgs.k8s.io/core:/stable:/v1.35/deb/Release.key
      repo_url: "https://pkgs.k8s.io/core:/stable:/v1.35/deb/ /"
      package:
      - "kubectl"
#  - role: emacs
  - role: cimon-io.asdf
    asdf_user: "{{ ansible_facts['user_id'] }}"
    asdf_group: "{{ ansible_facts['user_gid'] }}"
    asdf_plugins:
    - name: golang
      versions:
      - "1.25.7"
