---
- name: set up a development environment
  connection: local
  hosts: localhost
  vars:
    user: ellie
  tasks:
  - name: install zsh
    block:
    - apt:
        name: zsh
      become: true
    - user:
        name: "{{ user }}"
        shell: /bin/zsh
  - name: "general utilities"
    block:
    - apt:
        name:
        - man
      become: true
  - name: install emacs
    block:
    - apt:
        name:
        - emacs25
        - fonts-inconsolata
      become: true
    - git:
        repo: "https://github.com/syl20bnr/spacemacs"
        dest: "/home/{{ user }}/.emacs.d"
        update: no
        version: develop
  - name: install rust env
    block:
    - command: "curl -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path"
      args:
        creates: "~/.cargo/bin/rustup"
    - command: "~/.cargo/bin/rustup toolchain add nightly"
      args:
        creates: "~/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu"
    - command: "~/.cargo/bin/cargo +nightly install racer"
      args:
        creates: "~/.cargo/bin/racer"
    # racer requires source
    - command: "~/.cargo/bin/rustup component add rust-src"
      args:
        creates: "~/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/src"
      

